# Định danh dự án
sonar.projectKey=SoftSkill25_fix
sonar.projectName=SoftSkill25_fix
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=build/web/WEB-INF/classes
sonar.host.url=http://localhost:9000
sonar.login=sqa_456fe51821a6809772f20943c8263231eba2472d



